try {
    throw Error('blah blah'); 
  } catch (e) {
    console.log(e); 
  }
  console.log('Throw error caught and catched')
  
  
  